"""Auto-generated response models for newAd."""
from typing import Any, List, Optional

from pydantic import Field

from ..common import LingXingModel


class AdreportAdvertiserListList(LingXingModel):
    """list sub-structure."""
    advertiser_id: Optional[str] = Field(None, description="广告主id")
    advertiser_name: Optional[str] = Field(None, description="广告主名称")
    status: Optional[int] = Field(None, description="状态 0禁用, 1启用")

class AdreportAdvertiserListResponse(LingXingModel):
    """查询沃尔玛广告主列表."""
    total: Optional[int] = Field(None, description="总数")
    list: Optional[List[AdreportAdvertiserListList]] = Field(None, description="是")


class AdreportProductorderanalysisListList(LingXingModel):
    """list sub-structure."""
    key: Optional[str] = Field(None, description="sub_total 汇总行 group_type= hourly 时对应小时 group_type =weekly 对应周")
    store_orders: Optional[str] = Field(None, description="店铺订单")
    store_orders_percent: Optional[str] = Field(None, description="店铺订单百分比")
    store_units: Optional[str] = Field(None, description="店铺销量")
    store_units_percent: Optional[str] = Field(None, description="店铺销量百分比")
    store_sales: Optional[str] = Field(None, description="店铺销售额")
    store_sales_percent: Optional[str] = Field(None, description="店铺销售额百分比")
    ad_orders: Optional[str] = Field(None, description="广告订单")
    ad_orders_percent: Optional[str] = Field(None, description="广告订单百分比")
    ad_sales: Optional[str] = Field(None, description="广告销售额")
    ad_units: Optional[str] = Field(None, description="广告销量")
    ad_units_percent: Optional[str] = Field(None, description="广告销量百分比")
    spend: Optional[str] = Field(None, description="花费")
    impressions: Optional[str] = Field(None, description="曝光")
    clicks: Optional[str] = Field(None, description="点击")
    ad_sales_percent: Optional[str] = Field(None, description="广告销售额百分比")
    spend_percent: Optional[str] = Field(None, description="花费百分比")
    acos: Optional[str] = Field(None, description="acos")
    ad_spend_store_percent: Optional[str] = Field(None, description="广告花费占比")
    ad_order_store_percent: Optional[str] = Field(None, description="广告订单占比")
    as_sales_store_percent: Optional[str] = Field(None, description="广告销售额占比")
    ad_units_store_percent: Optional[str] = Field(None, description="广告销量占比")
    impression_percent: Optional[str] = Field(None, description="曝光百分比")
    clicks_percent: Optional[str] = Field(None, description="点击百分比")
    roas: Optional[str] = Field(None, description="roas")
    ctr: Optional[str] = Field(None, description="ctr")
    cpc: Optional[str] = Field(None, description="cpc")
    cvr: Optional[str] = Field(None, description="cvr")
    cpa: Optional[str] = Field(None, description="cpa")
    key_chart: Optional[str] = Field(None, description="group_type= hourly 对应小时的描述 group_type =weekly 周的描述")
    key_table: Optional[str] = Field(None, description="group_type= hourly 对应小时的描述 group_type =weekly 周的描述")

class AdreportProductorderanalysisListResponse(LingXingModel):
    """出单时段分析（产品）."""
    list: Optional[List[AdreportProductorderanalysisListList]] = Field(None, description="是")
    total: Optional[int] = Field(None, description="是")


class BasedataAccountListResponse(LingXingModel):
    """查询广告账号列表."""
    total: Optional[int] = Field(None, description="总数")
    sid: Optional[str] = Field(None, description="店铺id 1.type为seller时，返回sid 2.type为vendor时，sid的值暂时为profile_id(不建议使用，后续可能变更) 3.type为dsp时，为null")
    profile_id: Optional[str] = Field(None, description="亚马逊店铺数字id")
    country_code: Optional[str] = Field(None, description="国家code")
    currency_code: Optional[str] = Field(None, description="币种")
    status: Optional[int] = Field(None, description="账号状态： -1 删除 0 停止同步 1 正常 2 授权异常")
    name: Optional[str] = Field(None, description="账号名称")
    type: Optional[str] = Field(None, description="类型： dsp seller vendor")


class DspreportOrderListResponse(LingXingModel):
    """查询DSP报告列表-订单."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[str] = Field(None, description="亚马逊店铺数字id")
    order_id: Optional[str] = Field(None, description="订单id")
    order_name: Optional[str] = Field(None, description="订单名称")
    advertiser_id: Optional[str] = Field(None, description="广告主id")
    advertiser_name: Optional[str] = Field(None, description="广告主名称")
    order_start_date: Optional[str] = Field(None, description="开始时间")
    order_end_date: Optional[str] = Field(None, description="结束时间")
    order_budget: Optional[str] = Field(None, description="预算")
    spends: Optional[str] = Field(None, description="花费")
    sales: Optional[str] = Field(None, description="销售额")
    orders: Optional[str] = Field(None, description="订单数")
    impressions: Optional[str] = Field(None, description="曝光")
    viewable_impressions: Optional[str] = Field(None, description="可见展示次数")
    clicks: Optional[str] = Field(None, description="点击")
    dpv: Optional[str] = Field(None, description="商品详情页浏览次数")
    total_add_to_cart: Optional[str] = Field(None, description="加购次数")
    order_currency: Optional[str] = Field(None, description="币种")
    ad_units: Optional[str] = Field(None, description="销量")


class NewadAbareportResponse(LingXingModel):
    """ABA搜索词报告-按周维度."""
    url: Optional[str] = Field(None, description="文件下载地址 【下载的文件为zip格式，常用解压工具解压即可】")
    data_start_time: Optional[str] = Field(None, description="报表日期")
    report_period: Optional[str] = Field(None, description="报表类型：WEEK")
    country: Optional[str] = Field(None, description="国家代码")


class NewadApilogstandardOperateBefore(LingXingModel):
    """operate_before sub-structure."""
    code: Optional[str] = Field(None, description="操作类型编码")
    value: Optional[str] = Field(None, description="操作对象值")

class NewadApilogstandardOperateAfter(LingXingModel):
    """operate_after sub-structure."""
    code: Optional[str] = Field(None, description="操作类型编码")
    value: Optional[str] = Field(None, description="操作对象值")

class NewadApilogstandardResponse(LingXingModel):
    """操作日志（新）."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字ID")
    sponsored_type: Optional[str] = Field(None, description="广告类型：sp、sb、sd")
    operate_type: Optional[str] = Field(None, description="对象类型")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    campaign_name: Optional[float] = Field(None, description="广告活动名称")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    object_id: Optional[float] = Field(None, description="广告对象id")
    ad_group_name: Optional[str] = Field(None, description="广告组名称")
    object_name: Optional[str] = Field(None, description="广告对象名称")
    function_name: Optional[str] = Field(None, description="功能来源")
    change_type: Optional[str] = Field(None, description="操作类型：create 创建，update 更新")
    operate_before: Optional[List[NewadApilogstandardOperateBefore]] = Field(None, description="操作前")
    operate_after: Optional[List[NewadApilogstandardOperateAfter]] = Field(None, description="操作后")
    user_id: Optional[int] = Field(None, description="用户id")
    user_name: Optional[str] = Field(None, description="用户名")
    operate_time: Optional[str] = Field(None, description="操作时间 - 站点时间")


class NewadHsaadgroupreportsResponse(LingXingModel):
    """SB广告组报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    vtr: Optional[float] = Field(None, description="vtr")
    vctr: Optional[float] = Field(None, description="vctr")
    report_date: Optional[str] = Field(None, description="报告日期")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    new_to_brand_orders: Optional[float] = Field(None, description="品牌新买家订单数量")
    new_to_brand_order_percentage: Optional[float] = Field(None, description="品牌新买家订单百分比")
    new_to_brand_order_rate: Optional[float] = Field(None, description="品牌新买家转换率")
    new_to_brand_sales: Optional[float] = Field(None, description="品牌新买家销售额")
    new_to_brand_units: Optional[float] = Field(None, description="品牌新买家销量")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交量")


class NewadHsaadgroupsResponse(LingXingModel):
    """SB广告组."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    name: Optional[str] = Field(None, description="名称")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后一次更新时间")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadHsacampaignreportsResponse(LingXingModel):
    """SB广告活动报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    vtr: Optional[float] = Field(None, description="vtr")
    vctr: Optional[float] = Field(None, description="vctr")
    report_date: Optional[str] = Field(None, description="报告日期")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    new_to_brand_orders: Optional[float] = Field(None, description="品牌新买家订单数量")
    new_to_brand_order_percentage: Optional[float] = Field(None, description="品牌新买家订单百分比")
    new_to_brand_order_rate: Optional[float] = Field(None, description="品牌新买家转换率")
    new_to_brand_sales: Optional[float] = Field(None, description="品牌新买家销售额")
    new_to_brand_units: Optional[float] = Field(None, description="品牌新买家销量")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交量")


class OpenapiNewadHsacampaignsTags(LingXingModel):
    """tags sub-structure."""
    parent: Optional[str] = Field(None, description="父标签")
    child: Optional[str] = Field(None, description="子标签")

class NewadHsacampaignsResponse(LingXingModel):
    """SB广告活动."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="广告活动名称")
    budget: Optional[float] = Field(None, description="预算")
    budget_type: Optional[str] = Field(None, description="预算类型")
    start_date: Optional[str] = Field(None, description="开始日期")
    state: Optional[str] = Field(None, description="状态")
    serving_status: Optional[str] = Field(None, description="服务状态")
    bid_optimization: Optional[float] = Field(None, description="自动竞价")
    creative: Optional[str] = Field(None, description="广告创意结构【由于亚马逊api升级原因，该字段已废弃】，可通过[SB广告创意](docs/newAd/baseData/sbAdHasProductAds)creative字段获取")
    landing_page: Optional[str] = Field(None, description="广告着陆页")
    bid_multiplier: Optional[float] = Field(None, description="自定义竞价调整")
    end_date: Optional[str] = Field(None, description="结束日期")
    portfolio_id: Optional[float] = Field(None, description="广告组合ID")
    creative_type: Optional[str] = Field(None, description="创意类型【由于亚马逊api升级原因，该字段已废弃】，可通过[SB广告创意](docs/newAd/baseData/sbAdHasProductAds)creative_type字段获取")
    tags: Optional[List[OpenapiNewadHsacampaignsTags]] = Field(None, description="标签信息")


class NewadHsanegativekeywordsResponse(LingXingModel):
    """SB否定关键词."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    keyword_id: Optional[float] = Field(None, description="关键词ID")
    keyword_text: Optional[str] = Field(None, description="关键词")
    state: Optional[str] = Field(None, description="状态")
    match_type: Optional[str] = Field(None, description="匹配类别")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadHsanegativetargetsResponse(LingXingModel):
    """SB否定商品投放."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="投放ID")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    expression_type: Optional[str] = Field(None, description="表达式类别")
    expression: Optional[str] = Field(None, description="表达式")
    resolved_expression: Optional[str] = Field(None, description="解析的表达式")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadHsapurchasedasinreportsResponse(LingXingModel):
    """SB广告归因于广告的购买报告."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    report_date: Optional[str] = Field(None, description="报告日期")
    campaign_name: Optional[str] = Field(None, description="广告活动名称")
    campaign_id: Optional[float] = Field(None, description="广告活动id 【亚马逊官方解释：如果是非SB2，则campaign_id为空】")
    ad_group_name: Optional[str] = Field(None, description="广告组名称")
    ad_group_id: Optional[float] = Field(None, description="广告组id 【亚马逊官方解释：如果是非SB2，则ad_group_id为空】")
    asin: Optional[str] = Field(None, description="已购买的asin")
    attribution_type: Optional[str] = Field(None, description="引流类型 ： Promoted 促销 Brand Halo 品牌光环")
    sales14d: Optional[float] = Field(None, description="14天总销售额")
    orders14d: Optional[float] = Field(None, description="14天总订单数")
    units_sold14d: Optional[float] = Field(None, description="14天总件数")
    new_to_brand_sales14d: Optional[float] = Field(None, description="14天新客户订单销售额")
    new_to_brand_purchases14d: Optional[float] = Field(None, description="14天新客户订单")
    new_to_brand_units_sold14d: Optional[float] = Field(None, description="14天新客户订单件数")
    new_to_brand_sales_percentage14d: Optional[float] = Field(None, description="14天新客户订单销售额百分比")
    new_to_brand_purchases_percentage14d: Optional[float] = Field(None, description="14天新客户订单百分比")
    new_to_brand_units_sold_percentage14d: Optional[float] = Field(None, description="14天新客户订单件数百分比")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交量")


class NewadListhsakeywordplacementreportResponse(LingXingModel):
    """SB关键词-广告位报告."""
    total: Optional[int] = Field(None, description="总数")
    report_date: Optional[str] = Field(None, description="报告日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    match_type: Optional[str] = Field(None, description="匹配方式")
    keyword_id: Optional[float] = Field(None, description="关键词id")
    keyword_text: Optional[str] = Field(None, description="关键词内容")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    clicks: Optional[float] = Field(None, description="点击")
    cost: Optional[float] = Field(None, description="花费")
    impressions: Optional[float] = Field(None, description="曝光")
    orders: Optional[float] = Field(None, description="订单数")
    new_to_brand_orders: Optional[float] = Field(None, description="品牌新买家订单数量")
    new_to_brand_units: Optional[float] = Field(None, description="品牌新买家销量")
    new_to_brand_order_percentage: Optional[float] = Field(None, description="品牌新买家订单百分比")
    new_to_brand_order_rate: Optional[float] = Field(None, description="品牌新买家转换率")
    new_to_brand_sales: Optional[float] = Field(None, description="品牌新买家销售额")
    sales: Optional[float] = Field(None, description="销售额")
    creative_type: Optional[str] = Field(None, description="广告类型： default=》SB video=》SBV")
    placement_type: Optional[int] = Field(None, description="广告位类型： 1 Other Placements 2 Other on-Amazon 3 Top of Search")


class NewadListhsatargetingreportResponse(LingXingModel):
    """SB广告的投放报告."""
    total: Optional[int] = Field(None, description="总数")
    impressions: Optional[int] = Field(None, description="曝光量")
    clicks: Optional[int] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报告日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    keyword_id: Optional[float] = Field(None, description="关键词id，当target_type为keyword或ALL时出现")
    target_id: Optional[float] = Field(None, description="商品投放id，当target_type为producttarget或ALL时出现")
    creative_type: Optional[str] = Field(None, description="广告类型：default表示SB类型, video表示SBV类型")
    orders: Optional[float] = Field(None, description="订单")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    sales: Optional[float] = Field(None, description="销售额")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    new_to_brand_orders: Optional[float] = Field(None, description="品牌新买家订单数量")
    new_to_brand_order_percentage: Optional[float] = Field(None, description="品牌新买家订单百分比")
    new_to_brand_order_rate: Optional[float] = Field(None, description="品牌新买家转换率")
    new_to_brand_sales: Optional[float] = Field(None, description="品牌新买家销售额")
    new_to_brand_units: Optional[float] = Field(None, description="品牌新买家销量")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交量")


class NewadPortfoliosResponse(LingXingModel):
    """广告组合."""
    total: Optional[int] = Field(None, description="总数")
    portfolio_id: Optional[float] = Field(None, description="广告组合id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="名称")
    budget: Optional[str] = Field(None, description="广告组合预算信息【json格式】： null 无预算上限 amout 预算金额 policy 预算策略【dateRange、monthlyRecurring】 startDate 应用预算开始日期 endDate 应用预算的结束日期")
    in_budget: Optional[float] = Field(None, description="当前广告组合是否在预算范围内： 0 超出预算 1 在范围内")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSbadgrouphourdataResponse(LingXingModel):
    """SB广告组小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    cvr: Optional[int] = Field(None, description="订单数/点击")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpc: Optional[float] = Field(None, description="花费/点击")
    roas: Optional[float] = Field(None, description="销售额/花费")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSbadplacementhourdataResponse(LingXingModel):
    """SB广告位小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cvr: Optional[int] = Field(None, description="订单数/点击")
    roas: Optional[float] = Field(None, description="销售额/花费")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    cpc: Optional[float] = Field(None, description="花费/点击")
    acos: Optional[float] = Field(None, description="花费/销售额")
    placement: Optional[str] = Field(None, description="广告位")


class NewadSbcampaignhourdataResponse(LingXingModel):
    """SB广告活动小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cvr: Optional[int] = Field(None, description="订单数/点击")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    roas: Optional[float] = Field(None, description="销售额/花费")


class NewadSbdivideasinreportsResponse(LingXingModel):
    """SB分摊."""
    total: Optional[int] = Field(None, description="总数")
    report_date: Optional[float] = Field(None, description="报告日期")
    profile_id: Optional[float] = Field(None, description="profile_id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    department_id: Optional[float] = Field(None, description="-")
    ad_group_id: Optional[str] = Field(None, description="-")
    transaction_uuid: Optional[str] = Field(None, description="设置分摊的事务ID,用于追踪具体的分摊规则")
    asin: Optional[float] = Field(None, description="-")
    sku: Optional[float] = Field(None, description="-")
    impressions: Optional[float] = Field(None, description="-")
    clicks: Optional[str] = Field(None, description="点击数")
    spends: Optional[list] = Field(None, description="广告花费")
    orders: Optional[list] = Field(None, description="订单数")
    sales: Optional[list] = Field(None, description="广告销售额")
    units_sold: Optional[list] = Field(None, description="销售件数")
    same_orders: Optional[list] = Field(None, description="直接订单数")
    same_sales: Optional[list] = Field(None, description="直接广告销售额")
    same_units_sold: Optional[list] = Field(None, description="直接销售件数")
    divide_asin_md5: Optional[list] = Field(None, description="md5(ad_group_id, asin, sku)")
    percent: Optional[list] = Field(None, description="分摊比例")


class NewadSbtargethourdataResponse(LingXingModel):
    """SB投放小时数据."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    impressions: Optional[float] = Field(None, description="曝光量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpc: Optional[float] = Field(None, description="花费/点击")
    roas: Optional[float] = Field(None, description="销售额/花费")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    group_id: Optional[float] = Field(None, description="广告组id")
    targeting_id: Optional[float] = Field(None, description="投放id")
    targeting: Optional[str] = Field(None, description="投放表达式")


class NewadSbtargetingResponse(LingXingModel):
    """SB广告的投放."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    keyword_id: Optional[float] = Field(None, description="关键词ID")
    keyword_text: Optional[str] = Field(None, description="关键词文本")
    keyword_bid: Optional[float] = Field(None, description="关键词竞价")
    keyword_state: Optional[str] = Field(None, description="关键词状态")
    match_type: Optional[str] = Field(None, description="匹配类型")
    target_id: Optional[float] = Field(None, description="商品定位ID")
    expression: Optional[str] = Field(None, description="表达式")
    target_bid: Optional[float] = Field(None, description="商品定位竞价")
    target_state: Optional[str] = Field(None, description="商品定位状态")
    resolved_expression: Optional[str] = Field(None, description="商品定位解析表达式")
    targeting_type: Optional[str] = Field(None, description="投放类型")
    ads_type: Optional[str] = Field(None, description="广告类型")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")


class NewadSdadgrouphourdataResponse(LingXingModel):
    """SD广告组小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSdadgroupreportsResponse(LingXingModel):
    """SD广告组报表."""
    total: Optional[int] = Field(None, description="总数")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    tactic: Optional[str] = Field(None, description="投放类型")
    report_date: Optional[str] = Field(None, description="报表日期")
    view_impressions: Optional[float] = Field(None, description="可见展示量")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")


class NewadSdadgroupsResponse(LingXingModel):
    """SD广告组."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="广告组名称")
    default_bid: Optional[float] = Field(None, description="默认竞价")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[str] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")
    bid_optimization: Optional[str] = Field(None, description="优化建议")


class NewadSdadvertisehourdataResponse(LingXingModel):
    """SD广告小时数据."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    campaign_id: Optional[float] = Field(None, description="店铺id")
    ad_id: Optional[float] = Field(None, description="广告id")
    asin: Optional[str] = Field(None, description="asin")
    targeting: Optional[str] = Field(None, description="投放表达式【agg_dimension=-both_ad_target 时返回字段】")
    targeting_id: Optional[float] = Field(None, description="投放id【agg_dimension=-both_ad_target 时返回字段】")
    msku: Optional[str] = Field(None, description="msku")
    impressions: Optional[float] = Field(None, description="曝光量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpc: Optional[float] = Field(None, description="花费/点击")
    roas: Optional[float] = Field(None, description="销售额/花费")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSdcampaignhourdataResponse(LingXingModel):
    """SD广告活动小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    roas: Optional[float] = Field(None, description="销售额/花费")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpc: Optional[float] = Field(None, description="花费/点击")


class NewadSdcampaignreportsResponse(LingXingModel):
    """SD广告活动报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    tactic: Optional[str] = Field(None, description="投放类型")
    report_date: Optional[str] = Field(None, description="报表日期")
    view_impressions: Optional[float] = Field(None, description="可见展示次数")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")


class OpenapiNewadSdcampaignsTags(LingXingModel):
    """tags sub-structure."""
    parent: Optional[str] = Field(None, description="父标签")
    child: Optional[str] = Field(None, description="子标签")

class NewadSdcampaignsResponse(LingXingModel):
    """SD广告活动."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="广告活动名称")
    tactic: Optional[str] = Field(None, description="投放类型")
    cost_type: Optional[str] = Field(None, description="竞价类型")
    budget_type: Optional[str] = Field(None, description="预算类型")
    budget: Optional[float] = Field(None, description="预算")
    start_date: Optional[str] = Field(None, description="开始日期")
    end_date: Optional[str] = Field(None, description="结束日期")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新日期")
    state: Optional[str] = Field(None, description="状态")
    serving_status: Optional[str] = Field(None, description="服务状态")
    portfolio_id: Optional[float] = Field(None, description="广告组合ID")
    tags: Optional[List[OpenapiNewadSdcampaignsTags]] = Field(None, description="标签信息")


class NewadSdnegativetargetsResponse(LingXingModel):
    """SD否定商品定位."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="商品定位ID")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    expression_type: Optional[str] = Field(None, description="表达式类别")
    expression: Optional[str] = Field(None, description="表达式")
    resolved_expression: Optional[str] = Field(None, description="解析的表达式")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新日期")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSdproductadreportsResponse(LingXingModel):
    """SD广告商品报表."""
    total: Optional[int] = Field(None, description="总数")
    ad_id: Optional[float] = Field(None, description="商品广告id")
    asin: Optional[str] = Field(None, description="ASIN")
    sku: Optional[str] = Field(None, description="msku")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    tactic: Optional[str] = Field(None, description="投放类型")
    report_date: Optional[str] = Field(None, description="报表日期")
    view_impressions: Optional[float] = Field(None, description="可见展示量")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")


class NewadSdproductadsResponse(LingXingModel):
    """SD广告商品."""
    total: Optional[int] = Field(None, description="总数")
    ad_id: Optional[float] = Field(None, description="商品广告ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    state: Optional[str] = Field(None, description="状态")
    sku: Optional[str] = Field(None, description="SKU")
    asin: Optional[str] = Field(None, description="ASIN")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSdtargethourdataResponse(LingXingModel):
    """SD投放小时数据."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_id: Optional[float] = Field(None, description="广告id【聚合维度为：both_ad_target时，该字段有数据】")
    asin: Optional[str] = Field(None, description="asin【聚合维度为：both_ad_target时，该字段有数据】")
    msku: Optional[str] = Field(None, description="msku【聚合维度为：both_ad_target时，该字段有数据】")
    impressions: Optional[float] = Field(None, description="曝光量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    cpc: Optional[float] = Field(None, description="花费/点击")
    roas: Optional[float] = Field(None, description="销售额/花费")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    group_id: Optional[float] = Field(None, description="广告组id")
    targeting_id: Optional[float] = Field(None, description="投放id")
    targeting: Optional[str] = Field(None, description="投放表达式")


class NewadSdtargetreportsResponse(LingXingModel):
    """SD商品定位报表."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="商品定位ID")
    targeting_type: Optional[str] = Field(None, description="投放类别")
    targeting_text: Optional[str] = Field(None, description="投放内容")
    targeting_expression: Optional[str] = Field(None, description="投放表达式")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    tactic: Optional[str] = Field(None, description="投放类型")
    report_date: Optional[str] = Field(None, description="报表日期")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    view_impressions: Optional[float] = Field(None, description="可见展示量")


class NewadSdtargetsResponse(LingXingModel):
    """SD商品定位."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="商品定位ID")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    expression_type: Optional[str] = Field(None, description="表达式类别")
    expression: Optional[str] = Field(None, description="表达式")
    bid: Optional[float] = Field(None, description="竞价")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")
    resolved_expression: Optional[str] = Field(None, description="解析的表达式")


class NewadSpadgrouphourdataResponse(LingXingModel):
    """SP广告组小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时： 0 0-1点之间 1 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSpadgroupreportsResponse(LingXingModel):
    """SP广告组报表."""
    total: Optional[int] = Field(None, description="总数")
    ad_group_id: Optional[int] = Field(None, description="广告组id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(1d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    same_units_1d: Optional[float] = Field(None, description="直接成交量(1d)【show_detail=1时返回字段】")
    same_units_7d: Optional[float] = Field(None, description="直接成交量(7d)【show_detail=1时返回字段】")
    same_units_14d: Optional[float] = Field(None, description="直接成交量(14d)【show_detail=1时返回字段】")
    same_units_30d: Optional[float] = Field(None, description="直接成交量(30d)【show_detail=1时返回字段】")


class NewadSpadgroupsResponse(LingXingModel):
    """SP广告组."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动ID")
    ad_group_id: Optional[float] = Field(None, description="广告组ID")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="广告组名称")
    default_bid: Optional[float] = Field(None, description="默认竞价")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")
    bid_optimization: Optional[str] = Field(None, description="优化建议")


class NewadSpadplacementhourdataResponse(LingXingModel):
    """SP广告位小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    placement: Optional[str] = Field(None, description="广告位")
    hour: Optional[float] = Field(None, description="小时： 0 0-1点之间 1 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    units: Optional[float] = Field(None, description="销量")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    ctr: Optional[float] = Field(None, description="点击/曝光")


class NewadSpadvertisehourdataResponse(LingXingModel):
    """SP广告小时数据."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_id: Optional[float] = Field(None, description="广告id")
    msku: Optional[str] = Field(None, description="msku")
    asin: Optional[dict] = Field(None, description="asin")
    impressions: Optional[dict] = Field(None, description="曝光量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[dict] = Field(None, description="花费")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    units: Optional[float] = Field(None, description="销量")
    match_type: Optional[str] = Field(None, description="匹配方式（当聚合维度为：both_ad_target 该字段有值）")
    targeting_id: Optional[float] = Field(None, description="投放id（当聚合维度为：both_ad_target 该字段有值）")
    targeting: Optional[str] = Field(None, description="投放表达式（当聚合维度为：both_ad_target 该字段有值）")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSpcampaignhourdataResponse(LingXingModel):
    """SP广告活动小时数据."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时： 0 0-1点之间 1 1-2点之间 以此类推")
    cost: Optional[float] = Field(None, description="花费")
    clicks: Optional[float] = Field(None, description="点击量")
    impressions: Optional[float] = Field(None, description="曝光量")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    cpc: Optional[float] = Field(None, description="花费/点击")


class NewadSpcampaignreportsResponse(LingXingModel):
    """SP广告活动报表."""
    total: Optional[int] = Field(None, description="总数")
    targeting_type: Optional[str] = Field(None, description="投放类型")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(1d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")
    same_units: Optional[float] = Field(None, description="直接成交量")
    same_units_1d: Optional[float] = Field(None, description="直接成交量(1d)【show_detail=1时返回字段】")
    same_units_7d: Optional[float] = Field(None, description="直接成交量(7d)【show_detail=1时返回字段】")
    same_units_14d: Optional[float] = Field(None, description="直接成交量(14d)【show_detail=1时返回字段】")
    same_units_30d: Optional[float] = Field(None, description="直接成交量(30d)【show_detail=1时返回字段】")


class OpenapiNewadSpcampaignsTags(LingXingModel):
    """tags sub-structure."""
    parent: Optional[str] = Field(None, description="父标签")
    child: Optional[str] = Field(None, description="子标签")

class NewadSpcampaignsResponse(LingXingModel):
    """SP广告活动."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    name: Optional[str] = Field(None, description="广告活动名称")
    campaign_type: Optional[str] = Field(None, description="广告活动类型")
    targeting_type: Optional[str] = Field(None, description="投放类型")
    premium_bid_adjustment: Optional[float] = Field(None, description="溢价报价调整")
    daily_budget: Optional[float] = Field(None, description="每日预算")
    start_date: Optional[str] = Field(None, description="起始日期")
    end_date: Optional[str] = Field(None, description="结束日期")
    creation_date: Optional[float] = Field(None, description="创建日期")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    state: Optional[str] = Field(None, description="状态")
    serving_status: Optional[str] = Field(None, description="服务状态")
    bidding: Optional[str] = Field(None, description="竞价策略【json格式】")
    portfolio_id: Optional[float] = Field(None, description="广告组合id")
    tags: Optional[List[OpenapiNewadSpcampaignsTags]] = Field(None, description="标签信息")


class NewadSpkeywordreportsResponse(LingXingModel):
    """SP关键词报表."""
    total: Optional[int] = Field(None, description="总数")
    keyword_id: Optional[float] = Field(None, description="关键词id")
    match_type: Optional[str] = Field(None, description="匹配类型")
    keyword_text: Optional[str] = Field(None, description="关键词")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(1d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    same_units_1d: Optional[float] = Field(None, description="直接成交量(1d)【show_detail=1时返回字段】")
    same_units_7d: Optional[float] = Field(None, description="直接成交量(7d)【show_detail=1时返回字段】")
    same_units_14d: Optional[float] = Field(None, description="直接成交量(14d)【show_detail=1时返回字段】")
    same_units_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")


class NewadSpkeywordsResponse(LingXingModel):
    """SP关键词."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    keyword_id: Optional[float] = Field(None, description="关键词id")
    keyword_text: Optional[str] = Field(None, description="关键词文本")
    bid: Optional[float] = Field(None, description="竞价")
    state: Optional[str] = Field(None, description="状态")
    match_type: Optional[str] = Field(None, description="匹配类型")
    creation_date: Optional[float] = Field(None, description="创建日期")
    last_updated_date: Optional[float] = Field(None, description="最近更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSpnegativetargetsorkeywordsResponse(LingXingModel):
    """SP否定投放."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    target_id: Optional[float] = Field(None, description="投放id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    negative_type: Optional[str] = Field(None, description="否定类型： negativeKeyword 否定关键词 negativeAsin 否定ASIN negativeBrand 否定品牌")
    negative_text: Optional[str] = Field(None, description="否定内容：【按类型显示】 否定关键词：显示否定关键词的文本 否定ASIN：显示ASIN码 否定品牌：显示品牌名称")
    negative_match_type: Optional[str] = Field(None, description="否定匹配方式： 否定关键词：negativeExact、negativePhrase 否定ASIN和否定品牌：返回空字符串")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建时间")
    last_updated_date: Optional[float] = Field(None, description="最后更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSpproductadreportsResponse(LingXingModel):
    """SP广告商品报表."""
    total: Optional[int] = Field(None, description="总数")
    ad_id: Optional[float] = Field(None, description="商品广告id")
    asin: Optional[str] = Field(None, description="asin")
    sku: Optional[str] = Field(None, description="sku")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(1d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    same_units_1d: Optional[float] = Field(None, description="直接成交量(1d)【show_detail=1时返回字段】")
    same_units_7d: Optional[float] = Field(None, description="直接成交量(7d)【show_detail=1时返回字段】")
    same_units_14d: Optional[float] = Field(None, description="直接成交量(14d)【show_detail=1时返回字段】")
    same_units_30d: Optional[float] = Field(None, description="直接成交量(30d)【show_detail=1时返回字段】")


class NewadSpproductadsResponse(LingXingModel):
    """SP广告商品."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    ad_id: Optional[float] = Field(None, description="商品广告id")
    state: Optional[str] = Field(None, description="状态")
    sku: Optional[str] = Field(None, description="MSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    creation_date: Optional[float] = Field(None, description="创建日期")
    last_updated_date: Optional[float] = Field(None, description="最近更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")


class NewadSptargethourdataResponse(LingXingModel):
    """SP投放小时数据."""
    total: Optional[int] = Field(None, description="总数")
    profile_id: Optional[float] = Field(None, description="店铺id")
    report_date: Optional[str] = Field(None, description="报告日期")
    hour: Optional[float] = Field(None, description="小时: 0 表示0-1点之间 1 表示 1-2点之间 以此类推")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_id: Optional[float] = Field(None, description="广告id【agg_dimension = both_ad_target 的时候才返回】")
    asin: Optional[str] = Field(None, description="是")
    msku: Optional[str] = Field(None, description="是")
    match_type: Optional[str] = Field(None, description="匹配方式【agg_dimension=-both_ad_target 时返回该字段】")
    targeting_id: Optional[float] = Field(None, description="投放id【agg_dimension=-both_ad_target 时返回该字段】")
    targeting: Optional[str] = Field(None, description="投放表达式【agg_dimension=-both_ad_target 时返回该字段】")
    placement: Optional[str] = Field(None, description="广告位【当agg_dimension = both_target_placement 的时候才返回】")
    impressions: Optional[float] = Field(None, description="曝光量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    same_orders: Optional[float] = Field(None, description="直接成交订单")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接销售额")
    sales: Optional[float] = Field(None, description="销售额")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    units: Optional[float] = Field(None, description="销量")
    ctr: Optional[float] = Field(None, description="点击/曝光")
    cpc: Optional[float] = Field(None, description="花费/点击")
    cvr: Optional[float] = Field(None, description="订单数/点击")
    cpa: Optional[float] = Field(None, description="花费/订单数")
    acos: Optional[float] = Field(None, description="花费/销售额")
    roas: Optional[float] = Field(None, description="销售额/花费")
    group_id: Optional[float] = Field(None, description="广告组id")


class NewadSptargetreportsResponse(LingXingModel):
    """SP商品定位报表."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="投放id")
    targeting_type: Optional[str] = Field(None, description="投放类别")
    targeting_expression: Optional[str] = Field(None, description="投放表达式")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    same_orders_1d: Optional[float] = Field(None, description="直接成交订单数(1d)【show_detail=1时返回字段】")
    same_orders_7d: Optional[float] = Field(None, description="直接成交订单数(7d)【show_detail=1时返回字段】")
    same_orders_14d: Optional[float] = Field(None, description="直接成交订单数(14d)【show_detail=1时返回字段】")
    same_orders_30d: Optional[float] = Field(None, description="直接成交订单数(30d)【show_detail=1时返回字段】")
    orders: Optional[float] = Field(None, description="订单数")
    orders_1d: Optional[float] = Field(None, description="订单数(1d)【show_detail=1时返回字段】")
    orders_7d: Optional[float] = Field(None, description="订单数(7d)【show_detail=1时返回字段】")
    orders_30d: Optional[float] = Field(None, description="订单数(30d)【show_detail=1时返回字段】")
    orders_14d: Optional[float] = Field(None, description="订单数(14d)【show_detail=1时返回字段】")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    same_sales_1d: Optional[float] = Field(None, description="直接成交销售额(1d)【show_detail=1时返回字段】")
    same_sales_7d: Optional[float] = Field(None, description="直接成交销售额(7d)【show_detail=1时返回字段】")
    same_sales_14d: Optional[float] = Field(None, description="直接成交销售额(14d)【show_detail=1时返回字段】")
    same_sales_30d: Optional[float] = Field(None, description="直接成交销售额(30d)【show_detail=1时返回字段】")
    sales: Optional[float] = Field(None, description="销售额")
    sales_1d: Optional[float] = Field(None, description="销售额(1d)【show_detail=1时返回字段】")
    sales_7d: Optional[float] = Field(None, description="销售额(7d)【show_detail=1时返回字段】")
    sales_14d: Optional[float] = Field(None, description="销售额(14d)【show_detail=1时返回字段】")
    sales_30d: Optional[float] = Field(None, description="销售额(30d)【show_detail=1时返回字段】")
    units: Optional[float] = Field(None, description="销量")
    units_1d: Optional[float] = Field(None, description="销量(1d)【show_detail=1时返回字段】")
    units_7d: Optional[float] = Field(None, description="销量(7d)【show_detail=1时返回字段】")
    units_14d: Optional[float] = Field(None, description="销量(14d)【show_detail=1时返回字段】")
    units_30d: Optional[float] = Field(None, description="销量(30d)【show_detail=1时返回字段】")
    same_units: Optional[float] = Field(None, description="直接成交销量")
    same_units_1d: Optional[float] = Field(None, description="直接成交量(1d)【show_detail=1时返回字段】")
    same_units_7d: Optional[float] = Field(None, description="直接成交量(7d)【show_detail=1时返回字段】")
    same_units_14d: Optional[float] = Field(None, description="直接成交量(14d)【show_detail=1时返回字段】")
    same_units_30d: Optional[float] = Field(None, description="直接成交量(30d)【show_detail=1时返回字段】")


class NewadSptargetsResponse(LingXingModel):
    """SP商品定位."""
    total: Optional[int] = Field(None, description="总数")
    target_id: Optional[float] = Field(None, description="商品定位id")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    expression_type: Optional[str] = Field(None, description="表达式类别")
    expression: Optional[str] = Field(None, description="表达式")
    bid: Optional[float] = Field(None, description="竞价")
    state: Optional[str] = Field(None, description="状态")
    creation_date: Optional[float] = Field(None, description="创建日期")
    last_updated_date: Optional[float] = Field(None, description="最近更新时间")
    serving_status: Optional[str] = Field(None, description="服务状态")
    resolved_expression: Optional[str] = Field(None, description="已解析的表达式")


class NewadSpcampaignplacementreportsResponse(LingXingModel):
    """SP广告位报告."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    campaign_name: Optional[str] = Field(None, description="广告活动名称")
    campaign_status: Optional[str] = Field(None, description="广告活动状态")
    placement_type: Optional[int] = Field(None, description="广告位类型：1 Other Placements 2 Other on-Amazon 3 Top of Search")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")


class NewadSpasinreportsResponse(LingXingModel):
    """SP已购买商品报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    asin: Optional[str] = Field(None, description="ASIN")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交销量")


class NewadQuerywordreportsResponse(LingXingModel):
    """SP用户搜索词报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    keyword_id: Optional[float] = Field(None, description="关键词id")
    keyword_text: Optional[str] = Field(None, description="用户搜索词")
    match_type: Optional[str] = Field(None, description="匹配类型")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交销量")


class NewadHsacampaignplacementreportsResponse(LingXingModel):
    """SB广告活动-广告位报告."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    campaign_name: Optional[str] = Field(None, description="广告活动名称")
    placement_type: Optional[int] = Field(None, description="广告位类型")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")


class NewadHsaquerywordreportsResponse(LingXingModel):
    """SB用户搜索词报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    keyword_id: Optional[float] = Field(None, description="关键词id")
    keyword_text: Optional[str] = Field(None, description="用户搜索词")
    match_type: Optional[str] = Field(None, description="匹配类型")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交销量")


class NewadSdasinreportsResponse(LingXingModel):
    """SD已购买商品报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    asin: Optional[str] = Field(None, description="ASIN")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交销量")


class NewadSdmatchtargetreportsResponse(LingXingModel):
    """SD匹配的目标报表."""
    total: Optional[int] = Field(None, description="总数")
    campaign_id: Optional[float] = Field(None, description="广告活动id")
    ad_group_id: Optional[float] = Field(None, description="广告组id")
    target_id: Optional[float] = Field(None, description="投放id")
    targeting_type: Optional[str] = Field(None, description="投放类别")
    targeting_expression: Optional[str] = Field(None, description="投放表达式")
    impressions: Optional[float] = Field(None, description="展示量")
    clicks: Optional[float] = Field(None, description="点击量")
    cost: Optional[float] = Field(None, description="花费")
    report_date: Optional[str] = Field(None, description="报表日期")
    profile_id: Optional[float] = Field(None, description="亚马逊店铺数字id")
    same_orders: Optional[float] = Field(None, description="直接成交订单数")
    orders: Optional[float] = Field(None, description="订单数")
    same_sales: Optional[float] = Field(None, description="直接成交销售额")
    sales: Optional[float] = Field(None, description="销售额")
    units: Optional[float] = Field(None, description="销量")
    same_units: Optional[float] = Field(None, description="直接成交销量")


class AdReportAdvertiserListResponse(LingXingModel):
    """查询沃尔玛-广告-广告主列表 (/basicOpen/adReport/advertiser/list)."""
    msg: Optional[str] = None
