"""Auto-generated response models for SourceData."""
from typing import Any, List, Optional

from pydantic import Field

from ..common import LingXingModel


class OpenapiMwsreportAdjustmentlistResponse(LingXingModel):
    """查询亚马逊源报表-盘存记录."""
    total: Optional[int] = Field(None, description="[int]")
    sid: Optional[int] = Field(None, description="[int]")
    report_date: Optional[str] = Field(None, description="[string]")
    transaction_item_id: Optional[str] = Field(None, description="[string]")
    fnsku: Optional[str] = Field(None, description="[string]")
    msku: Optional[str] = Field(None, description="[string]")
    item_name: Optional[str] = Field(None, description="[string]")
    fulfillment_center_id: Optional[str] = Field(None, description="[string]")
    quantity: Optional[int] = Field(None, description="[int]")
    reason: Optional[str] = Field(None, description="[string]")
    reason_text: Optional[str] = Field(None, description="[string]")
    disposition: Optional[str] = Field(None, description="[string]")


class FbaReportRemovallistsResponse(LingXingModel):
    """查询亚马逊源报表-移除货件（旧）."""
    sid: Optional[int] = Field(None, description="店铺id")
    uuid: Optional[str] = Field(None, description="UUID")
    request_timestamp: Optional[int] = Field(None, description="时间戳")
    request_date: Optional[str] = Field(None, description="创建时间")
    order_id: Optional[str] = Field(None, description="订单ID")
    shipment_date: Optional[str] = Field(None, description="发货日期")
    sku: Optional[str] = Field(None, description="MSKU")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    disposition: Optional[str] = Field(None, description="disposition")
    shipped_quantity: Optional[float] = Field(None, description="发货量")
    carrier: Optional[str] = Field(None, description="承运商")
    tracking_number: Optional[str] = Field(None, description="物流跟踪号")
    shipment_status: Optional[str] = Field(None, description="状态")
    mid: Optional[float] = Field(None, description="站点ID")
    seller_name: Optional[str] = Field(None, description="店铺名称")
    marketplace: Optional[str] = Field(None, description="站点名称")


class MwsReportAllordersResponse(LingXingModel):
    """查询亚马逊源报表-所有订单."""
    amazon_order_id: Optional[str] = Field(None, description="亚马逊订单号")
    merchant_order_id: Optional[str] = Field(None, description="卖家为订单提供的唯一编号")
    last_updated_time: Optional[str] = Field(None, description="订单最近更新时间")
    purchase_date: Optional[str] = Field(None, description="下单日期-格式化当地时间（当地时间, 时区）")
    purchase_date_locale: Optional[str] = Field(None, description="下单日期-对应亚马逊当地日期（不建议使用）")
    purchase_date_local: Optional[str] = Field(None, description="下单日期-店铺当地时间")
    shipment_date: Optional[str] = Field(None, description="发货时间-UTC时间")
    order_status: Optional[str] = Field(None, description="订单的当前状态")
    fulfillment_channel: Optional[str] = Field(None, description="订单的配送方式： Amazon 亚马逊配送 (AFN) Merchant 卖家自行配送 (MFN)")
    sales_channel: Optional[str] = Field(None, description="下单渠道")
    order_channel: Optional[str] = Field(None, description="CBA/WBA 订单下单的子渠道")
    url: Optional[str] = Field(None, description="链接")
    ship_service_level: Optional[str] = Field(None, description="配送服务类型")
    sku: Optional[str] = Field(None, description="MSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    product_name: Optional[str] = Field(None, description="品名")
    item_status: Optional[str] = Field(None, description="该商品在订单内的当前状态")
    quantity: Optional[float] = Field(None, description="此商品的购买数量")
    currency: Optional[str] = Field(None, description="币种")
    item_price: Optional[str] = Field(None, description="买家为商品支付的金额")
    item_tax: Optional[str] = Field(None, description="买家为商品税支付的金额")
    shipping_price: Optional[str] = Field(None, description="买家支付的运费金额")
    shipping_tax: Optional[str] = Field(None, description="买家为运费税支付的金额")
    gift_wrap_price: Optional[str] = Field(None, description="买家为礼品包装支付的金额")
    gift_wrap_tax: Optional[str] = Field(None, description="买家为礼品包装税支付的金额")
    item_promotion_discount: Optional[str] = Field(None, description="应用于订单商品的所有促销折扣的总和")
    ship_promotion_discount: Optional[str] = Field(None, description="应用于配送的促销折扣")
    promotion_ids: Optional[str] = Field(None, description="应用于此订单商品的所有商品促销的列表")
    pid: Optional[int] = Field(None, description="本地产品id")
    local_sku: Optional[str] = Field(None, description="本地产品SKU")
    local_name: Optional[str] = Field(None, description="本地产品品名")
    sid: Optional[int] = Field(None, description="店铺id")
    total: Optional[int] = Field(None, description="总数")


class MwsReportDailyinventoryResponse(LingXingModel):
    """查询亚马逊源报表-每日库存."""
    snapshot_date: Optional[str] = Field(None, description="快照时间")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    sku: Optional[str] = Field(None, description="SKU")
    product_name: Optional[str] = Field(None, description="品名")
    quantity: Optional[float] = Field(None, description="数量")
    fulfillment_center_id: Optional[str] = Field(None, description="存储库存的运营中心")
    detailed_disposition: Optional[str] = Field(None, description="商品状态（例如，可售、残损等）")
    country: Optional[str] = Field(None, description="库存存放地所在的国家/地区代码")


class MwsReportFbaordersResponse(LingXingModel):
    """查询亚马逊源报表-FBA订单."""
    amazon_order_id: Optional[str] = Field(None, description="订单号")
    shipment_id: Optional[str] = Field(None, description="配送ID")
    shipment_item_id: Optional[str] = Field(None, description="配送子ID")
    amazon_order_item_id: Optional[str] = Field(None, description="订单子项ID")
    purchase_date: Optional[str] = Field(None, description="下单日期")
    payments_date: Optional[str] = Field(None, description="支付日期")
    shipment_date: Optional[str] = Field(None, description="配送日期（零时区）")
    reporting_date: Optional[str] = Field(None, description="报表日期")
    estimated_arrival_date: Optional[str] = Field(None, description="预计送达日期")
    sku: Optional[str] = Field(None, description="SKU")
    product_name: Optional[str] = Field(None, description="品名")
    quantity_shipped: Optional[float] = Field(None, description="数量")
    currency: Optional[str] = Field(None, description="币种")
    item_price: Optional[str] = Field(None, description="商品金额")
    item_tax: Optional[str] = Field(None, description="商品税")
    shipping_price: Optional[str] = Field(None, description="运费金额")
    shipping_tax: Optional[str] = Field(None, description="运费税")
    gift_wrap_price: Optional[str] = Field(None, description="礼品包装费")
    gift_wrap_tax: Optional[str] = Field(None, description="礼品包装税")
    ship_service_level: Optional[str] = Field(None, description="配送级别")
    item_promotion_discount: Optional[str] = Field(None, description="订单商品促销折扣")
    ship_promotion_discount: Optional[str] = Field(None, description="配送的促销折扣")
    carrier: Optional[str] = Field(None, description="运输方")
    tracking_number: Optional[str] = Field(None, description="快递号")
    fulfillment_channel: Optional[str] = Field(None, description="配送方式： 亚马逊配送 (AFN) 卖家自行配送 (MFN)")
    points_granted: Optional[str] = Field(None, description="亚马逊授予买家的积分")


class MwsReportGetafnfulfillablequantityResponse(LingXingModel):
    """查询亚马逊源报表-FBA可售库存."""
    sid: Optional[int] = Field(None, description="店铺id")
    seller_sku: Optional[str] = Field(None, description="销售SKU")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    condition_type: Optional[str] = Field(None, description="商品成色")
    country: Optional[str] = Field(None, description="国家二字码")
    afn_fulfillable_quantity: Optional[float] = Field(None, description="FBA可售数量")
    gmt_modified: Optional[str] = Field(None, description="更新时间")


class MwsReportGetamazonfulfilledshipmentslistResponse(LingXingModel):
    """查询亚马逊源报表—Amazon Fulfilled Shipments."""
    sid: Optional[int] = Field(None, description="店铺id")
    amazon_order_id: Optional[str] = Field(None, description="亚马逊为订单提供的可显示的唯一编号")
    merchant_order_id: Optional[str] = Field(None, description="卖家为订单提供的唯一标识")
    shipment_id: Optional[str] = Field(None, description="加密的亚马逊货件编号")
    shipment_item_id: Optional[str] = Field(None, description="加密的亚马逊货件商品编号")
    amazon_order_item_id: Optional[str] = Field(None, description="亚马逊为订单内商品提供的唯一可显示编号")
    merchant_order_item_id: Optional[str] = Field(None, description="为订单内商品提供的唯一标识")
    purchase_date: Optional[str] = Field(None, description="订单下单日期（报表时间，含时区）")
    purchase_date_locale: Optional[str] = Field(None, description="订单下单日期（站点时间，含时区）")
    payments_date: Optional[str] = Field(None, description="买家付款处理完成的日期（报表时间，含时区）")
    payments_date_locale: Optional[str] = Field(None, description="买家付款处理完成的日期（站点时间，含时区）")
    shipment_date: Optional[str] = Field(None, description="亚马逊完成货件（已配送）的日期（报表时间，含时区）")
    shipment_date_locale: Optional[str] = Field(None, description="亚马逊完成货件（已配送）的日期（站点时间，含时区）")
    reporting_date: Optional[str] = Field(None, description="提供报告数据的日期（报表时间，含时区）")
    reporting_date_locale: Optional[str] = Field(None, description="提供报告数据的日期（站点时间，含时区）")
    sku: Optional[str] = Field(None, description="卖家为商品定义的唯一标识")
    product_name: Optional[str] = Field(None, description="商品的简称，在商品详情页面上和浏览器的标题栏以粗体字显示")
    quantity_shipped: Optional[float] = Field(None, description="此商品已配送的数量")
    currency: Optional[str] = Field(None, description="购物使用的货币")
    item_price: Optional[str] = Field(None, description="买家为商品支付的金额。金额是总金额，不是单价。")
    item_tax: Optional[str] = Field(None, description="买家支付的商品税。金额是总金额，不是单价。")
    shipping_price: Optional[str] = Field(None, description="买家支付的运费。金额是总金额，不是单价。")
    shipping_tax: Optional[str] = Field(None, description="买家支付的运费税。金额是总金额，不是单价。")
    gift_wrap_price: Optional[str] = Field(None, description="买家为礼品包装支付的金额。金额是总金额，不是单价。")
    gift_wrap_tax: Optional[str] = Field(None, description="买家支付的礼品包装税。金额是总金额，不是单价。")
    ship_service_level: Optional[str] = Field(None, description="买家期望卖家使用的配送服务类型（例如，标准配送与加急配送）")
    ship_country: Optional[str] = Field(None, description="ISO 3166 标准的收件地址的国家/地区二字代码")
    bill_country: Optional[str] = Field(None, description="ISO 3166 标准的账单地址的国家/地区二字代码")
    item_promotion_discount: Optional[str] = Field(None, description="订单商品的促销折扣")
    ship_promotion_discount: Optional[str] = Field(None, description="配送费的促销折扣")
    carrier: Optional[str] = Field(None, description="配送包裹的承运人")
    tracking_number: Optional[str] = Field(None, description="包裹的承运人追踪编码")
    estimated_arrival_date: Optional[str] = Field(None, description="预计送达买家地址的日期（报表时间，含时区）")
    estimated_arrival_date_locale: Optional[str] = Field(None, description="预计送达买家地址的日期（站点时间，含时区）")
    fulfillment_center_id: Optional[str] = Field(None, description="配送订单的运营中心的唯一标识")
    fulfillment_channel: Optional[str] = Field(None, description="说明订单的配送方式：亚马逊物流网络 (AFN) 或卖家自配送 (MFN)")
    sales_channel: Optional[str] = Field(None, description="订单来源")
    points_granted: Optional[str] = Field(None, description="积分成本（日本站）")
    total: Optional[int] = Field(None, description="总数")


class MwsReportGetfbainventoryeventdetaillistResponse(LingXingModel):
    """查询亚马逊源报表——Inventory Event Detail."""
    sid: Optional[int] = Field(None, description="店铺id")
    snapshot_date: Optional[str] = Field(None, description="快照时间")
    snapshot_date_locale: Optional[str] = Field(None, description="快照时间")
    snapshot_date_timestamp: Optional[int] = Field(None, description="快照时间对应时间戳")
    snapshot_date_report: Optional[Any] = Field(None, description="是")
    transaction_type: Optional[Any] = Field(None, description="是")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    sku: Optional[str] = Field(None, description="SKU")
    product_name: Optional[Any] = Field(None, description="是")
    fulfillment_center_id: Optional[Any] = Field(None, description="是")
    quantity: Optional[Any] = Field(None, description="是")
    disposition: Optional[Any] = Field(None, description="是")
    total: Optional[int] = Field(None, description="总数")


class MwsReportManageinventoryResponse(LingXingModel):
    """查询亚马逊源报表-FBA库存."""
    sku: Optional[str] = Field(None, description="MSKU")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    product_name: Optional[str] = Field(None, description="品名")
    condition: Optional[str] = Field(None, description="商品的状况")
    mfn_listing_exists: Optional[str] = Field(None, description="商品是否由卖家自行配送")
    mfn_fulfillable_quantity: Optional[float] = Field(None, description="您的配送网络中可取件、包装和配送的商品数量")
    afn_listing_exists: Optional[str] = Field(None, description="商品是否由亚马逊物流配送")
    afn_warehouse_quantity: Optional[float] = Field(None, description="亚马逊运营中心内某个 SKU 的已处理商品数量")
    afn_fulfillable_quantity: Optional[float] = Field(None, description="亚马逊运营中心内某个 SKU 可取件、包装和配送的商品数量")
    afn_unsellable_quantity: Optional[float] = Field(None, description="亚马逊运营中心内某个 SKU 处于不可售状况的商品数量")
    afn_reserved_quantity: Optional[float] = Field(None, description="亚马逊运营中心内某个 SKU 目前正在进行内部处理（如取件、包装和配送或留作测量、取样等）的商品数量")
    afn_total_quantity: Optional[float] = Field(None, description="入库货件或亚马逊运营中心内某个 SKU 的商品总数量：(afn-total-quantity) = (afn-warehouse-quantity) + (afn-inbound-working-quantity) + (afn-inbound-shipped-quantity) + (afn-inbound-receiving-quantity)")
    per_unit_volume: Optional[Any] = Field(None, description="是")
    afn_inbound_working_quantity: Optional[float] = Field(None, description="您已通知亚马逊的入库货件中某个 SKU 的商品数量")
    afn_inbound_shipped_quantity: Optional[float] = Field(None, description="您已通知亚马逊并提供追踪编码的入库货件中某个 SKU 的商品数量")
    afn_inbound_receiving_quantity: Optional[float] = Field(None, description="某个 SKU 抵达亚马逊运营中心等待处理的商品数量")
    your_price: Optional[float] = Field(None, description="您当前的销售价格")
    cg_price: Optional[float] = Field(None, description="采购：采购成本（人民币）")
    landed_price: Optional[float] = Field(None, description="卖家自己产品的销售价格")
    gmt_modified: Optional[str] = Field(None, description="更新时间")


class MwsReportRefundordersTag(LingXingModel):
    """tag sub-structure."""
    tag_name: Optional[str] = Field(None, description="标签名称")
    tag_color: Optional[str] = Field(None, description="标签颜色")

class MwsReportRefundordersResponse(LingXingModel):
    """查询亚马逊源报表-FBA退货订单."""
    sid: Optional[int] = Field(None, description="店铺id")
    order_id: Optional[str] = Field(None, description="订单号")
    local_sku: Optional[str] = Field(None, description="本地产品sku")
    product_name: Optional[str] = Field(None, description="品名")
    sku: Optional[str] = Field(None, description="MSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    quantity: Optional[int] = Field(None, description="数量")
    return_date: Optional[str] = Field(None, description="退货时间【UTC时间】")
    return_date_locale: Optional[str] = Field(None, description="退货时间【站点时间】")
    purchase_date: Optional[str] = Field(None, description="订购时间【UTC时间】")
    purchase_date_locale: Optional[str] = Field(None, description="订购时间【站点时间】")
    gmt_modified: Optional[str] = Field(None, description="更新时间")
    fulfillment_center_id: Optional[str] = Field(None, description="存储库存的运营中心")
    detailed_disposition: Optional[str] = Field(None, description="商品状态属性")
    reason: Optional[str] = Field(None, description="退回原因")
    status: Optional[str] = Field(None, description="状态")
    license_plate_number: Optional[str] = Field(None, description="唯一序列号")
    customer_comments: Optional[str] = Field(None, description="买家评论")
    remark: Optional[str] = Field(None, description="备注")
    tag: Optional[List[MwsReportRefundordersTag]] = Field(None, description="标签信息")


class MwsReportRemovalordersResponse(LingXingModel):
    """查询亚马逊源报表-移除订单（旧）."""
    request_date: Optional[str] = Field(None, description="提交移除订单的日期")
    order_id: Optional[str] = Field(None, description="订单编号")
    order_type: Optional[str] = Field(None, description="移除订单类型（退货或弃置）")
    order_status: Optional[str] = Field(None, description="移除订单状态")
    last_updated_date: Optional[str] = Field(None, description="订单最近更新的日期")
    sku: Optional[str] = Field(None, description="SKU")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    disposition: Optional[str] = Field(None, description="商品状况")
    requested_quantity: Optional[int] = Field(None, description="移除订单中请求的此 FNSKU 的商品数量")
    cancelled_quantity: Optional[int] = Field(None, description="取消数量")
    disposed_quantity: Optional[int] = Field(None, description="已处置数量")
    shipped_quantity: Optional[int] = Field(None, description="已发货数量")
    in_process_quantity: Optional[int] = Field(None, description="处置中数量")
    removal_fee: Optional[str] = Field(None, description="移除费用")
    currency: Optional[str] = Field(None, description="币种")


class MwsReportReservedinventoryResponse(LingXingModel):
    """查询亚马逊源报表-预留库存."""
    sku: Optional[str] = Field(None, description="SKU")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    asin: Optional[str] = Field(None, description="ASIN")
    product_name: Optional[str] = Field(None, description="品名")
    reserved_qty: Optional[float] = Field(None, description="预留数量")
    reserved_customerorders: Optional[float] = Field(None, description="为买家订单预留的商品数量")
    reserved_fc_transfers: Optional[float] = Field(None, description="预留运营中心转运数量")
    reserved_fc_processing: Optional[float] = Field(None, description="预留运营中心处理中数量")
    gmt_modified: Optional[str] = Field(None, description="更新时间")


class MwsReportTransactionResponse(LingXingModel):
    """查询亚马逊源报表-交易明细."""
    sid: Optional[int] = Field(None, description="店铺id")
    is_to_b: Optional[int] = Field(None, description="是否为B2B订单：0 否【2c】，1 是")
    report_date_month: Optional[str] = Field(None, description="client_task的月份")
    report_index: Optional[int] = Field(None, description="报表行索引")
    date_str: Optional[str] = Field(None, description="原本的日期字符串")
    date_locale: Optional[str] = Field(None, description="当地日期")
    date_iso: Optional[str] = Field(None, description="ISO时间")
    settlement_id: Optional[str] = Field(None, description="结算编号")
    type: Optional[int] = Field(None, description="类型： 1 ORDER 2 REFUND 3 ADJUSTMENT 4 A_TO_Z_GUARANTEE_CLAIM 5 CHARGEBACK_REFUND 6 FBA_INVENTORY_FEE 7 SERVICE_FEE 8 LIGHTNING_DEAL_FEE 9 TRANSFER 10 ORDER_RETROCHARGE 11 REFUND_RETROCHARGE 12 CHARGE...")
    type_str: Optional[str] = Field(None, description="类型说明")
    order_id: Optional[str] = Field(None, description="订单号")
    sku: Optional[str] = Field(None, description="SKU")
    description: Optional[str] = Field(None, description="商品描述")
    quantity: Optional[float] = Field(None, description="商品数量")
    marketplace: Optional[str] = Field(None, description="销售市场")
    fulfillment: Optional[str] = Field(None, description="发货方式")
    order_city: Optional[str] = Field(None, description="城市")
    order_state: Optional[str] = Field(None, description="州")
    order_postal: Optional[str] = Field(None, description="邮编")
    product_sales: Optional[str] = Field(None, description="销售价格")
    product_sales_tax: Optional[str] = Field(None, description="销售税")
    currency: Optional[str] = Field(None, description="币种")
    shipping_credits: Optional[str] = Field(None, description="运费")
    shipping_credits_tax: Optional[str] = Field(None, description="运费税（荷兰，瑞典，沙特，阿联酋无该税费）")
    gift_wrap_credits: Optional[str] = Field(None, description="礼品包装费")
    gift_wrap_credits_tax: Optional[str] = Field(None, description="礼品包装税（荷兰，瑞典，沙特，阿联酋无该税费）")
    promotional_rebates: Optional[str] = Field(None, description="促销返点")
    promotional_rebates_tax: Optional[str] = Field(None, description="促销返点税（荷兰，瑞典，沙特，阿联酋无该税费）")
    sales_tax_collected: Optional[str] = Field(None, description="销售税（仅荷兰，瑞典，沙特，阿联酋有该税费）")
    marketplace_facilitator_tax: Optional[str] = Field(None, description="市场税")
    selling_fees: Optional[str] = Field(None, description="平台费（佣金）")
    fba_fees: Optional[str] = Field(None, description="FBA发货费")
    other_transaction_fees: Optional[str] = Field(None, description="其他交易费")
    other: Optional[str] = Field(None, description="其他费")
    total: Optional[str] = Field(None, description="总计")


class MwsReportV1GetamazonfulfilledshipmentslistResponse(LingXingModel):
    """查询亚马逊源报表—Amazon Fulfilled Shipments v1."""
    sid: Optional[int] = Field(None, description="店铺id")
    amazon_order_id: Optional[str] = Field(None, description="亚马逊为订单提供的可显示的唯一编号")
    merchant_order_id: Optional[str] = Field(None, description="卖家为订单提供的唯一标识")
    shipment_id: Optional[str] = Field(None, description="加密的亚马逊货件编号")
    shipment_item_id: Optional[str] = Field(None, description="加密的亚马逊货件商品编号")
    amazon_order_item_id: Optional[str] = Field(None, description="亚马逊为订单内商品提供的唯一可显示编号")
    merchant_order_item_id: Optional[str] = Field(None, description="为订单内商品提供的唯一标识")
    purchase_date: Optional[str] = Field(None, description="订单下单日期（报表时间，含时区）")
    purchase_date_locale: Optional[str] = Field(None, description="订单下单日期（站点时间，含时区）")
    payments_date: Optional[str] = Field(None, description="买家付款处理完成的日期（报表时间，含时区）")
    payments_date_locale: Optional[str] = Field(None, description="买家付款处理完成的日期（站点时间，含时区）")
    shipment_date: Optional[str] = Field(None, description="亚马逊完成货件（已配送）的日期（报表时间，含时区）")
    shipment_date_locale: Optional[str] = Field(None, description="亚马逊完成货件（已配送）的日期（站点时间，含时区）")
    reporting_date: Optional[str] = Field(None, description="提供报告数据的日期（报表时间，含时区）")
    reporting_date_locale: Optional[str] = Field(None, description="提供报告数据的日期（站点时间，含时区）")
    msku: Optional[str] = Field(None, description="亚马逊的sku（原sku）")
    product_name: Optional[str] = Field(None, description="商品的简称，在商品详情页面上和浏览器的标题栏以粗体字显示")
    quantity_shipped: Optional[float] = Field(None, description="此商品已配送的数量")
    currency: Optional[str] = Field(None, description="购物使用的货币")
    item_price: Optional[str] = Field(None, description="买家为商品支付的金额。金额是总金额，不是单价。")
    item_tax: Optional[str] = Field(None, description="买家支付的商品税。金额是总金额，不是单价。")
    shipping_price: Optional[str] = Field(None, description="买家支付的运费。金额是总金额，不是单价。")
    shipping_tax: Optional[str] = Field(None, description="买家支付的运费税。金额是总金额，不是单价。")
    gift_wrap_price: Optional[str] = Field(None, description="买家为礼品包装支付的金额。金额是总金额，不是单价。")
    gift_wrap_tax: Optional[str] = Field(None, description="买家支付的礼品包装税。金额是总金额，不是单价。")
    ship_service_level: Optional[str] = Field(None, description="买家期望卖家使用的配送服务类型（例如，标准配送与加急配送）")
    ship_country: Optional[str] = Field(None, description="ISO 3166 标准的收件地址的国家/地区二字代码")
    bill_country: Optional[str] = Field(None, description="ISO 3166 标准的账单地址的国家/地区二字代码")
    item_promotion_discount: Optional[str] = Field(None, description="订单商品的促销折扣")
    ship_promotion_discount: Optional[str] = Field(None, description="配送费的促销折扣")
    carrier: Optional[str] = Field(None, description="配送包裹的承运人")
    tracking_number: Optional[str] = Field(None, description="包裹的承运人追踪编码")
    estimated_arrival_date: Optional[str] = Field(None, description="预计送达买家地址的日期（报表时间，含时区）")
    estimated_arrival_date_locale: Optional[str] = Field(None, description="预计送达买家地址的日期（站点时间，含时区）")
    fulfillment_center_id: Optional[str] = Field(None, description="配送订单的运营中心的唯一标识")
    fulfillment_channel: Optional[str] = Field(None, description="说明订单的配送方式：亚马逊物流网络 (AFN) 或卖家自配送 (MFN)")
    sales_channel: Optional[str] = Field(None, description="订单来源")
    points_granted: Optional[str] = Field(None, description="积分成本（日本站）")
    local_name: Optional[str] = Field(None, description="品名")
    local_sku: Optional[str] = Field(None, description="本地sku")
    total: Optional[int] = Field(None, description="总数")


class MwsReportV1GetfbainventoryeventdetaillistResponse(LingXingModel):
    """查询亚马逊源表数据--Inventory Event Detail v1."""
    total: Optional[int] = Field(None, description="总数")
    sid: Optional[int] = Field(None, description="店铺id")
    snapshot_date: Optional[str] = Field(None, description="快照时间")
    snapshot_date_locale: Optional[str] = Field(None, description="快照时间")
    snapshot_date_timestamp: Optional[int] = Field(None, description="快照时间对应时间戳")
    snapshot_date_report: Optional[Any] = Field(None, description="是")
    transaction_type: Optional[Any] = Field(None, description="是")
    fnsku: Optional[str] = Field(None, description="FNSKU")
    msku: Optional[str] = Field(None, description="亚马逊sku（原 sku）")
    product_name: Optional[str] = Field(None, description="商品名称")
    fulfillment_center_id: Optional[str] = Field(None, description="存储库存的运营中心")
    quantity: Optional[float] = Field(None, description="数量")
    disposition: Optional[str] = Field(None, description="状况")
    local_name: Optional[str] = Field(None, description="品名")
    local_sku: Optional[str] = Field(None, description="本地sku")


class OrderFbaexchangeorderlistResponse(LingXingModel):
    """查询亚马逊源报表-FBA换货订单."""
    total: Optional[int] = Field(None, description="总数")
    order_hash: Optional[str] = Field(None, description="订单唯一hash【不是唯一键】")
    sid: Optional[int] = Field(None, description="店铺id")
    replacement_amazon_order_id: Optional[str] = Field(None, description="换货订单号")
    shipment_date: Optional[str] = Field(None, description="换货时间")
    asin: Optional[str] = Field(None, description="asin")
    seller_sku: Optional[str] = Field(None, description="msku")
    original_amazon_order_id: Optional[str] = Field(None, description="原始订单号")
    fulfillment_center_id: Optional[str] = Field(None, description="换货仓库")
    original_fulfillment_center_id: Optional[str] = Field(None, description="原始仓库")
    quantity: Optional[str] = Field(None, description="换货数量")
    replacement_reason_code: Optional[str] = Field(None, description="换货原因")
    sync_time: Optional[str] = Field(None, description="数据同步时间戳")


class OrderFbmreturnorderlistTagTypeIds(LingXingModel):
    """tag_type_ids sub-structure."""
    tag_name: Optional[str] = Field(None, description="标签名称")
    tag_color: Optional[str] = Field(None, description="标签颜色")

class OrderFbmreturnorderlistResponse(LingXingModel):
    """查询亚马逊源报表-FBM退货订单."""
    total: Optional[int] = Field(None, description="总数")
    id: Optional[int] = Field(None, description="订单id")
    order_hash: Optional[str] = Field(None, description="订单唯一hash")
    sid: Optional[int] = Field(None, description="店铺id")
    order_id: Optional[str] = Field(None, description="亚马逊订单id")
    order_date: Optional[str] = Field(None, description="订购时间")
    return_date: Optional[str] = Field(None, description="退货时间")
    return_status: Optional[str] = Field(None, description="退货状态")
    rma_id: Optional[str] = Field(None, description="RMA单号")
    label_type: Optional[str] = Field(None, description="标签类型")
    label_cost: Optional[str] = Field(None, description="标签费用")
    currency_code: Optional[str] = Field(None, description="币种")
    return_carrier: Optional[str] = Field(None, description="承运商")
    tracking_id: Optional[str] = Field(None, description="运单号")
    label_payer: Optional[str] = Field(None, description="标签支付方")
    a_to_z_claim: Optional[str] = Field(None, description="'A-to-Z'标签, N代表否，Y代表是")
    is_prime: Optional[str] = Field(None, description="'Prime'标签, N代表否，Y代表是")
    asin: Optional[str] = Field(None, description="asin")
    seller_sku: Optional[str] = Field(None, description="seller_sku【MSKU】")
    item_name: Optional[str] = Field(None, description="标题")
    return_quantity: Optional[float] = Field(None, description="退货数量")
    return_reason: Optional[str] = Field(None, description="退货原因")
    in_policy: Optional[str] = Field(None, description="是否符合政策：N代表否，Y代表是")
    return_type: Optional[str] = Field(None, description="退货类型")
    resolution: Optional[str] = Field(None, description="解决方法")
    invoice_number: Optional[str] = Field(None, description="发票号码")
    return_delivery_date: Optional[str] = Field(None, description="退货送达日期")
    order_amount: Optional[str] = Field(None, description="订单金额")
    order_quantity: Optional[int] = Field(None, description="商品信息--原始数量")
    safet_action_reason: Optional[str] = Field(None, description="Safe-T索赔原因")
    safet_claim_id: Optional[str] = Field(None, description="Saft-T索赔单号")
    safet_claim_state: Optional[str] = Field(None, description="Saft-T索赔状态")
    safet_claim_creation_time: Optional[str] = Field(None, description="Saft-T索赔时间")
    safet_claim_reimbursement_amount: Optional[str] = Field(None, description="Safe-T索赔金额")
    refunded_amount: Optional[str] = Field(None, description="退款金额")
    sync_time: Optional[int] = Field(None, description="同步数据时间戳")
    rma_id_provider: Optional[str] = Field(None, description="RMA单号提供者(amazon或者Merchant)")
    remark: Optional[str] = Field(None, description="备注")
    tag_type_ids: Optional[List[OrderFbmreturnorderlistTagTypeIds]] = Field(None, description="标签信息")
    local_sku: Optional[str] = Field(None, description="本地产品sku")
    local_name: Optional[str] = Field(None, description="品名")
    brand_title: Optional[str] = Field(None, description="品牌名")
    category_title_path: Optional[str] = Field(None, description="分类")
    country: Optional[str] = Field(None, description="国家")
    seller_name: Optional[str] = Field(None, description="店铺名")
    asin_url: Optional[str] = Field(None, description="asin地址")
    pic_url: Optional[str] = Field(None, description="产品图片")


class OrderRemovalorderlistnewResponse(LingXingModel):
    """查询亚马逊源报表-移除订单（新）."""
    seller_id: Optional[str] = Field(None, description="亚马逊店铺id")
    sid: Optional[int] = Field(None, description="店铺id【为0代表未确定订单店铺】")
    region: Optional[str] = Field(None, description="地区")
    request_date: Optional[str] = Field(None, description="订单日期")
    order_id: Optional[str] = Field(None, description="订单号")
    order_type: Optional[str] = Field(None, description="订单类型")
    order_status: Optional[str] = Field(None, description="订单状态")
    last_updated_date: Optional[str] = Field(None, description="更新时间")
    sku: Optional[str] = Field(None, description="msku")
    fnsku: Optional[str] = Field(None, description="fnsku")
    disposition: Optional[str] = Field(None, description="库存属性")
    requested_quantity: Optional[float] = Field(None, description="请求数量")
    cancelled_quantity: Optional[float] = Field(None, description="取消数量")
    disposed_quantity: Optional[float] = Field(None, description="已处置数量")
    shipped_quantity: Optional[float] = Field(None, description="已发货数量")
    in_process_quantity: Optional[float] = Field(None, description="处置中数量")
    removal_fee: Optional[str] = Field(None, description="移除费用")
    currency: Optional[str] = Field(None, description="币种")
    address_detail: Optional[str] = Field(None, description="配送地址")
    country_code: Optional[str] = Field(None, description="国家编码")
    local_sku: Optional[str] = Field(None, description="sku")
    local_name: Optional[str] = Field(None, description="品名")
    total: Optional[int] = Field(None, description="总数")


class FbaFbastockGetfbaagelistList(LingXingModel):
    """list sub-structure."""
    sid: Optional[int] = Field(None, description="店铺id")
    snapshot_date: Optional[str] = Field(None, description="生成报告的日期")
    sku: Optional[str] = Field(None, description="您分配给所售商品的唯一编码，由字母和数字组成")
    fnsku: Optional[str] = Field(None, description="亚马逊为存放在亚马逊运营中心并从亚马逊运营中心配送的商品分配的唯一编码，由字母和数字组成")
    asin: Optional[str] = Field(None, description="亚马逊为通过亚马逊销售的商品分配的唯一编码，由 10 个字母或数字组成")
    product_name: Optional[str] = Field(None, description="商品的名称")
    condition: Optional[str] = Field(None, description="商品的状况(例如，新品或二手)")
    available: Optional[str] = Field(None, description="可售(可售库存)数量")
    pending_removal_quantity: Optional[str] = Field(None, description="您请求退还或弃置的商品数量")
    inv_age_0_to_90_days: Optional[int] = Field(None, description="已在运营中心存放 0-90 天的可售商品数量")
    inv_age_91_to_180_days: Optional[int] = Field(None, description="已在运营中心存放 91-180 天的可售商品数量")
    inv_age_181_to_270_days: Optional[int] = Field(None, description="已在运营中心存放 181-270 天的可售商品数量")
    inv_age_271_to_365_days: Optional[int] = Field(None, description="已在运营中心存放 271-365 天的可售商品数量")
    inv_age_365_plus_days: Optional[str] = Field(None, description="已在运营中心存放超过 365 天的可售商品数量")
    currency: Optional[str] = Field(None, description="用于支付预计长期仓储费的货币")
    qty_to_be_charged_ltsf_6_mo: Optional[str] = Field(None, description="截至下一收费日期，已在亚马逊运营中心存放 180 至 365 天且需支付 180 天长期仓储费的可售商品数量")
    qty_to_be_charged_ltsf_12_mo: Optional[str] = Field(None, description="截至下一收费日期(每月 15 日)，已在运营中心存放超过 365 天的可售 商品数量")
    projected_ltsf_6_mo: Optional[str] = Field(None, description="在下一收费日期，已在运营中心存放 180 至 365 天的商品预计需要支付的长期仓储费")
    projected_ltsf_12_mo: Optional[str] = Field(None, description="截至下一收费日期(每月 15 日)，已在运营中心存放超过 365 天的商品的 预计长期仓储费")
    estimated_ltsf_next_charge: Optional[str] = Field(None, description="截至下一收费日期(每月 15 日)，在亚马逊运行中心存放超过365天的可售商品的数量预计的长期仓储费")
    units_shipped_t7: Optional[str] = Field(None, description="最近 7 天内已发货的商品数量")
    units_shipped_t30: Optional[str] = Field(None, description="最近 30 天内已发货的商品数量")
    units_shipped_t60: Optional[str] = Field(None, description="最近 60 天内已发货的商品数量")
    units_shipped_t90: Optional[str] = Field(None, description="最近 90 天内已发货的商品数量")
    alert: Optional[str] = Field(None, description="当商品存在低流量或低转化率提醒时会显示，低流量表明只有少数潜在买家查看了该商品信息，低转化率表明潜在买家查看了商品信息但最后并未跟进购买商品")
    your_price: Optional[str] = Field(None, description="您发布的商品价格")
    sales_price: Optional[str] = Field(None, description="您的促销价格(如果您正在促销该商品)")
    lowest_price_new_plus_shipping: Optional[str] = Field(None, description="此商品的新品在亚马逊商城的最低价格(含运费)")
    lowest_price_used: Optional[str] = Field(None, description="此商品的二手商品在亚马逊商城的最低价格(含运费)")
    recommended_action: Optional[str] = Field(None, description="建议您对库存执行的操作。建议的依据是您当前的买家需求，以及相对于不做任何操作，采取措施是否会降低您的成本")
    healthy_inventory_level: Optional[str] = Field(None, description="根据商品需求和您的成本，不属于冗余库存的库存数量。我们提供建议是为了帮助您达到这一库存水平")
    recommended_sales_price: Optional[str] = Field(None, description="有助于您根据当前库存设置来售出库存的建议促销价格。该值可能与最低价格或推荐报价价格不同。我们建议您在售出冗余库存之前维持该商品价格")
    recommended_sale_duration_days: Optional[str] = Field(None, description="如果建议您开展促销活动，则该数值是有助于您售出冗余库存的预计促销持续天数")
    recommended_removal_quantity: Optional[str] = Field(None, description="可以移除从而避免产生仓储费的预计商品数量")
    estimated_cost_savings_of_recommended_actions: Optional[str] = Field(None, description="与不采取任何操作(需要为相应库存支付仓储费)相比，采取建议操作预计可以节约的成本")
    sell_through: Optional[str] = Field(None, description="售出率为在过去 90 天内售出和已发货的商品数量除以此段时间内亚马逊 运营中心的平均可售库存量。追踪售出率可帮助您确定是否需要采取措施 来提高商品的流量或转化率")
    item_volume: Optional[str] = Field(None, description="商品的体积，计算方法是将最长边、次长边和最短边的值相乘。这些测量值通常是指商品的长度、宽度和高度")
    volume_unit_measurement: Optional[str] = Field(None, description="商品体积的计量单位")
    storage_type: Optional[str] = Field(None, description="可设置仓储限制的商品仓储类型分类")
    storage_volume: Optional[str] = Field(None, description="仓储容量等于此商品在亚马逊运营中心的总仓储使用量减去等待移除的商品的仓储使用量")
    marketplace: Optional[str] = Field(None, description="商品所在的亚马逊商城")
    product_group: Optional[str] = Field(None, description="区分图书和钟表或视频游戏等商品的独特商品分组")
    sales_rank: Optional[str] = Field(None, description="商品的当前排名。销售排名值的正负变化是过去 7 天排名上升(正)或下 降(负)名次")
    days_of_supply: Optional[str] = Field(None, description="根据商品的预期需求估算的您当前库存能够持续供货的天数")
    estimated_excess_quantity: Optional[str] = Field(None, description="预计冗余商品数量是根据您当前的销售速度和买家需求预测得出的积压商品数量。保留积压商品并支付仓储费比通过降价售出或移除积压商品来降低库存数量的成本更高")
    weeks_of_cover_t30: Optional[str] = Field(None, description="过去 30 天现货库存平均数除以同期售出的商品数量除以 4 周。对于某一 商品，如果您在过去 30 天(4 周)内售出 400 件，在亚马逊运营中心还 有 100 件可售，那么您基于过去 30 天销量的可维持周数为 1")
    weeks_of_cover_t90: Optional[str] = Field(None, description="过去 90 天现货库存平均数除以同期售出的商品数量除以 12 周。对于某一 商品，如果您在过去 90 天(12 周)内售出 400 件，在亚马逊运营中心平 均还有 10 件可售，那么您基于过去 90 天销量的可维持周数为 3.33")
    featuredoffer_price: Optional[str] = Field(None, description="在商品详情页面上显示加入购物车按钮的商品")
    sales_shipped_last_7_days: Optional[str] = Field(None, description="最近 7 天的已发货商品销量")
    sales_shipped_last_30_days: Optional[str] = Field(None, description="最近 30 天的已发货商品销量")
    sales_shipped_last_60_days: Optional[str] = Field(None, description="最近 60 天的已发货商品销量")
    sales_shipped_last_90_days: Optional[str] = Field(None, description="最近 90 天的已发货商品销量")
    inv_age_0_to_30_days: Optional[int] = Field(None, description="已在运营中心存放 30 天的可售商品数量")
    inv_age_31_to_60_days: Optional[int] = Field(None, description="已在运营中心存放 31-60 天的可售商品数量")
    inv_age_61_to_90_days: Optional[int] = Field(None, description="已在运营中心存放 61-90 天的可售商品数量")
    inv_age_181_to_330_days: Optional[int] = Field(None, description="已在运营中心存放 181-330 天的可售商品数量")
    inv_age_331_to_365_days: Optional[int] = Field(None, description="已在运营中心存放 331-365 天的可售商品数量")
    estimated_storage_cost_next_month: Optional[str] = Field(None, description="根据您当前的销售速度，从今天开始往后 30 天内所产生的预计仓储 费(月度仓储 + 长期仓储)。注意: 库存费用是基于您库存的最新每日快照中的数量得出，可能会 与您的实际库存数量不同")
    inbound_quantity: Optional[str] = Field(None, description="入库数量 = inbound-working + inbound-shipped + inbound receiving")
    inbound_working: Optional[str] = Field(None, description="处于“处理中”状态的货件数量")
    inbound_shipped: Optional[str] = Field(None, description="处于“已发货”状态的货件数量")
    inbound_received: Optional[str] = Field(None, description="处于“正在接收”状态的货件数量")
    no_sale_last_6_months: Optional[str] = Field(None, description="至少连续 6 个月未售出且在运营中心存放已超过 180 天的库存。如果您启 用可售库存自动移除服务，系统将在下一移除周期自动移除这些商品")

class FbaFbastockGetfbaagelistResponse(LingXingModel):
    """查询亚马逊源报表—库龄表."""
    list: Optional[List[FbaFbastockGetfbaagelistList]] = Field(None, description="数据列表")
    total: Optional[int] = Field(None, description="总数")


class StatisticRemovalshipmentListSellerName(LingXingModel):
    """seller_name sub-structure."""
    sid: Optional[str] = Field(None, description="店铺id")
    name: Optional[str] = Field(None, description="店铺名称")
    mid: Optional[str] = Field(None, description="站点id")
    marketplace: Optional[str] = Field(None, description="市场")

class StatisticRemovalshipmentListLocalInfo(LingXingModel):
    """local_info sub-structure."""
    local_sku: Optional[str] = Field(None, description="sku")
    local_name: Optional[str] = Field(None, description="品名")

class StatisticRemovalshipmentListDeliveryInfo(LingXingModel):
    """delivery_info sub-structure."""
    ship_postal_code: Optional[str] = Field(None, description="邮编")
    ship_state: Optional[str] = Field(None, description="配送地区")
    ship_city: Optional[str] = Field(None, description="配送城市")
    ship_country: Optional[str] = Field(None, description="配送国家")
    district: Optional[str] = Field(None, description="街道")
    county: Optional[str] = Field(None, description="县")
    phone: Optional[str] = Field(None, description="电话")
    address_line1: Optional[str] = Field(None, description="地址1")
    address_line2: Optional[str] = Field(None, description="地址2")
    address_line3: Optional[str] = Field(None, description="地址3")
    name: Optional[str] = Field(None, description="名称")
    address: Optional[str] = Field(None, description="配送地址")

class StatisticRemovalshipmentListResponse(LingXingModel):
    """查询亚马逊源报表-移除货件（新）."""
    total: Optional[int] = Field(None, description="总数")
    sid: Optional[int] = Field(None, description="店铺id")
    mid: Optional[int] = Field(None, description="站点id")
    seller_id: Optional[str] = Field(None, description="亚马逊店铺id")
    seller_account_name: Optional[str] = Field(None, description="店铺账号名称")
    marketplace: Optional[str] = Field(None, description="市场")
    uuid_new: Optional[str] = Field(None, description="业务标识【uuid_new+uuid_num_new可标记唯一移除货件行】")
    uuid_num_new: Optional[int] = Field(None, description="业务标识-序号【uuid_new+uuid_num_new可标记唯一移除货件行】")
    order_id: Optional[str] = Field(None, description="移除订单号")
    sku: Optional[str] = Field(None, description="seller_sku【MSKU】")
    fnsku: Optional[str] = Field(None, description="fnsku")
    disposition: Optional[str] = Field(None, description="disposition")
    shipped_quantity: Optional[int] = Field(None, description="发货数量")
    carrier: Optional[str] = Field(None, description="承运商")
    tracking_number: Optional[str] = Field(None, description="运单号")
    seller_name: Optional[List[StatisticRemovalshipmentListSellerName]] = Field(None, description="店铺名称")
    removal_order_type: Optional[str] = Field(None, description="移除货件类型")
    overseas_removal_order_no: Optional[str] = Field(None, description="移除入库单号")
    shipment_date: Optional[str] = Field(None, description="发货日期")
    shipment_date_timestamp: Optional[int] = Field(None, description="发货日期（时间戳）")
    request_date: Optional[str] = Field(None, description="创建时间")
    local_info: Optional[List[StatisticRemovalshipmentListLocalInfo]] = Field(None, description="本地产品信息")
    delivery_info: Optional[List[StatisticRemovalshipmentListDeliveryInfo]] = Field(None, description="配送信息")
