"""Auto-generated response models for TargetManage."""
from typing import List, Optional

from pydantic import Field

from ..common import LingXingModel


class ManagementStoreBatchoperateResponse(LingXingModel):
    """店铺维度-批量新增/更新目标."""
    sid: Optional[float] = Field(None, description="店铺id")
    reason: Optional[str] = Field(None, description="失败原因【返回操作失败对应数据的失败原因】")


class ManagementStoreBatchselectResponse(LingXingModel):
    """店铺维度-批量查询目标."""
    goal_name: Optional[str] = Field(None, description="目标名")
    sid: Optional[float] = Field(None, description="店铺id")
    name: Optional[str] = Field(None, description="店铺名")
    currency_code: Optional[str] = Field(None, description="币种")
    icon: Optional[str] = Field(None, description="币种符号")
    assess_year: Optional[int] = Field(None, description="目标年份")
    goal_amount1: Optional[float] = Field(None, description="1月目标值")
    goal_amount2: Optional[float] = Field(None, description="2月目标值")
    goal_amount3: Optional[float] = Field(None, description="3月目标值")
    goal_amount4: Optional[float] = Field(None, description="4月目标值")
    goal_amount5: Optional[float] = Field(None, description="5月目标值")
    goal_amount6: Optional[float] = Field(None, description="6月目标值")
    goal_amount7: Optional[float] = Field(None, description="7月目标值")
    goal_amount8: Optional[float] = Field(None, description="8月目标值")
    goal_amount9: Optional[float] = Field(None, description="9月目标值")
    goal_amount10: Optional[float] = Field(None, description="10月目标值")
    goal_amount11: Optional[float] = Field(None, description="11月目标值")
    goal_amount12: Optional[float] = Field(None, description="12月目标值")
    real_amount1: Optional[float] = Field(None, description="1月完成值")
    real_amount2: Optional[float] = Field(None, description="2月完成值")
    real_amount3: Optional[float] = Field(None, description="3月完成值")
    real_amount4: Optional[float] = Field(None, description="4月完成值")
    real_amount5: Optional[float] = Field(None, description="5月完成值")
    real_amount6: Optional[float] = Field(None, description="6月完成值")
    real_amount7: Optional[float] = Field(None, description="7月完成值")
    real_amount8: Optional[float] = Field(None, description="8月完成值")
    real_amount9: Optional[float] = Field(None, description="9月完成值")
    real_amount10: Optional[float] = Field(None, description="10月完成值")
    real_amount11: Optional[float] = Field(None, description="11月完成值")
    real_amount12: Optional[float] = Field(None, description="12月完成值")
    complete_rate_amount1: Optional[float] = Field(None, description="1月完成率")
    complete_rate_amount2: Optional[float] = Field(None, description="2月完成率")
    complete_rate_amount3: Optional[float] = Field(None, description="3月完成率")
    complete_rate_amount4: Optional[float] = Field(None, description="4月完成率")
    complete_rate_amount5: Optional[float] = Field(None, description="5月完成率")
    complete_rate_amount6: Optional[float] = Field(None, description="6月完成率")
    complete_rate_amount7: Optional[float] = Field(None, description="7月完成率")
    complete_rate_amount8: Optional[float] = Field(None, description="8月完成率")
    complete_rate_amount9: Optional[float] = Field(None, description="9月完成率")
    complete_rate_amount10: Optional[float] = Field(None, description="10月完成率")
    complete_rate_amount11: Optional[float] = Field(None, description="11月完成率")
    complete_rate_amount12: Optional[float] = Field(None, description="12月完成率")
    total_goal_amount: Optional[float] = Field(None, description="累计目标值")
    total_real_amount: Optional[float] = Field(None, description="累计完成值")
    total_complete_rate: Optional[float] = Field(None, description="累计完成率")
    create_user_id: Optional[float] = Field(None, description="创建用户id")
    create_user_name: Optional[str] = Field(None, description="创建用户名")
    update_user_id: Optional[float] = Field(None, description="更新用户id")
    update_user_name: Optional[str] = Field(None, description="更新用户名")
    gmt_create: Optional[str] = Field(None, description="创建时间")
    gmt_modified: Optional[str] = Field(None, description="更新时间")


class ManagementUserBatchoperateResponse(LingXingModel):
    """组织维度-批量新增/更新目标."""
    uid: Optional[float] = Field(None, description="用户名")
    reason: Optional[str] = Field(None, description="失败原因")


class ManagementUserBatchselectOrgs(LingXingModel):
    """orgs sub-structure."""
    org_id: Optional[str] = Field(None, description="部门id")
    org_name: Optional[str] = Field(None, description="部门名称")

class ManagementUserBatchselectResponse(LingXingModel):
    """组织维度-批量查询目标."""
    real_name: Optional[str] = Field(None, description="用户名")
    uid: Optional[str] = Field(None, description="uid")
    default_org: Optional[str] = Field(None, description="默认部门")
    default_org_id: Optional[str] = Field(None, description="默认部门id")
    orgs: Optional[List[ManagementUserBatchselectOrgs]] = Field(None, description="所有部门")
    currency_code: Optional[str] = Field(None, description="币种")
    icon: Optional[str] = Field(None, description="货币符号")
    assess_type: Optional[str] = Field(None, description="考核指标：1 销售额，2 销量")
    goal_value1: Optional[float] = Field(None, description="1月目标值")
    goal_value2: Optional[float] = Field(None, description="2月目标值")
    goal_value3: Optional[float] = Field(None, description="3月目标值")
    goal_value4: Optional[float] = Field(None, description="4月目标值")
    goal_value5: Optional[float] = Field(None, description="5月目标值")
    goal_value6: Optional[float] = Field(None, description="6月目标值")
    goal_value7: Optional[float] = Field(None, description="7月目标值")
    goal_value8: Optional[float] = Field(None, description="8月目标值")
    goal_value9: Optional[float] = Field(None, description="9月目标值")
    goal_value10: Optional[float] = Field(None, description="10月目标值")
    goal_value11: Optional[float] = Field(None, description="11月目标值")
    goal_value12: Optional[float] = Field(None, description="12月目标值")
    real_value1: Optional[float] = Field(None, description="1月完成值")
    real_value2: Optional[float] = Field(None, description="2月完成值")
    real_value3: Optional[float] = Field(None, description="3月完成值")
    real_value4: Optional[float] = Field(None, description="4月完成值")
    real_value5: Optional[float] = Field(None, description="5月完成值")
    real_value6: Optional[float] = Field(None, description="6月完成值")
    real_value7: Optional[float] = Field(None, description="7月完成值")
    real_value8: Optional[float] = Field(None, description="8月完成值")
    real_value9: Optional[float] = Field(None, description="9月完成值")
    real_value10: Optional[float] = Field(None, description="10月完成值")
    real_value11: Optional[float] = Field(None, description="11月完成值")
    real_value12: Optional[float] = Field(None, description="12月完成值")
    complete_rate1: Optional[float] = Field(None, description="1月完成率")
    complete_rate2: Optional[float] = Field(None, description="2月完成率")
    complete_rate3: Optional[float] = Field(None, description="3月完成率")
    complete_rate4: Optional[float] = Field(None, description="4月完成率")
    complete_rate5: Optional[float] = Field(None, description="5月完成率")
    complete_rate6: Optional[float] = Field(None, description="6月完成率")
    complete_rate7: Optional[float] = Field(None, description="7月完成率")
    complete_rate8: Optional[float] = Field(None, description="8月完成率")
    complete_rate9: Optional[float] = Field(None, description="9月完成率")
    complete_rate10: Optional[float] = Field(None, description="10月完成率")
    complete_rate11: Optional[float] = Field(None, description="11月完成率")
    complete_rate12: Optional[float] = Field(None, description="12月完成率")
    year_goal_value: Optional[float] = Field(None, description="年度目标值")
    year_real_value: Optional[float] = Field(None, description="年度完成值")
    complete_process: Optional[float] = Field(None, description="年度完成进度")
    create_user_id: Optional[float] = Field(None, description="目标创建用户id")
    create_user: Optional[str] = Field(None, description="目标创建用户")
    update_user_id: Optional[float] = Field(None, description="目标最后更新用户id")
    update_user: Optional[str] = Field(None, description="目标最后更新用户")
    gmt_create: Optional[str] = Field(None, description="创建时间")
    gmt_modified: Optional[str] = Field(None, description="更新时间")
